### ISSUE TITLE
[General] Project abandoned?

### ISSUE THREAD

**Issue by fridde** [OpenSkill/Datatable#42]
I know progress can be a bit slow sometimes, but the expected timeline stated in the docs and the current commit history don't match. 

I think this project is great, but installing a potentially abandoned unfinished repository seems a bit risky to me.

Would you mind commenting on the current status in the docs? Postponed, migrated, abandoned, "as-is", etc... Thanks!

**Comment by Chumper** [comment]
Hey, sorry for the lack of updates. 
I planned this as a successor to my other library with the help of @timgws but we both fell short on time.
I currently do not programm in PHP anymore and have a lot to do at work, so I do not plan actively develop  further on this. However I will gladly accept PRs and shift the ownership over to anybody who wants to contribute.

The basic funcionality is there with collections workin. The only thing missing is the database query part.
So if you only need collections, then this should be good to go, otherwise I would strongly suggest to use a package that has **active** support and development for the features you need.

I am sorry that I do not have the time anymore so from my side I would label it as `as is` and `abandoned` unless someone else will continue.

**Comment by timgws** [comment]
Haha, please do not mark this as abandoned.

I do actively use this project as is (it has all the required functionality for a number of my projects!)

That being said, both @chumper and I have access to accept PRs, so as long as you commit new features with unit tests, and it can be agreed that the commit either resolves an issue in the code, or adds functionality that is in the scope of this project, there is no reason why it would not be accepted.

**Comment by Chumper** [comment]
Sorry, I was then a bit too fast with my own thoughts. I will remove the note about that. BUt as I said, I currently have no plan to further develop this apart from PRs.

**Comment by timgws** [comment]
@fridde I would just like to quickly point out that #33 is talking about tagging and releasing 0.3.0.

The only reason this has not been yet is because of a specific bug that still exists (#26 - [CollectionProvider] Returned columns are empty) and I am not too sure on what the best way to resolve this issue is.

**Comment by fridde** [comment]
Thanks for your comments and for removing the "scary warning". 

It feels like it is much clearer now that this is a project in active use which just hasn't had the need for a bugfix lately. I'll be happy to use it.

Sorry for not getting back earlier. Busy days...
